// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import com.bytepoxic.core.model.AppRole;
import javax.persistence.Entity;

privileged aspect AppRole_Roo_Jpa_Entity {
    
    declare @type: AppRole: @Entity;
    
}
