// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import com.bytepoxic.core.model.BaseFullEntity;

privileged aspect BaseFullEntity_Roo_JavaBean {
    
    public boolean BaseFullEntity.isEnabled() {
        return this.enabled;
    }
    
    public void BaseFullEntity.setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
    
}
