// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import com.bytepoxic.core.model.BaseFullEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BaseFullEntity_Roo_Configurable {
    
    declare @type: BaseFullEntity: @Configurable;
    
}
