// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import com.bytepoxic.core.model.I18NableEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect I18NableEntity_Roo_Configurable {
    
    declare @type: I18NableEntity: @Configurable;
    
}
