// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.web.jsf;

import com.bytepoxic.core.web.jsf.BarBean;
import java.io.Serializable;

privileged aspect BarBean_Roo_Serializable {
    
    declare parents: BarBean implements Serializable;
    
    private static final long BarBean.serialVersionUID = 1L;
    
}
