// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.web.jsf;

import com.bytepoxic.core.web.jsf.NationalityBean;
import java.io.Serializable;

privileged aspect NationalityBean_Roo_Serializable {
    
    declare parents: NationalityBean implements Serializable;
    
    private static final long NationalityBean.serialVersionUID = 1L;
    
}
