// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.web.faces.bean.converter;

import com.bytepoxic.core.web.faces.bean.converter.LocationConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LocationConverter_Roo_Configurable {
    
    declare @type: LocationConverter: @Configurable;
    
}
