// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.example.model;

import com.bytepoxic.example.model.Bar;
import com.bytepoxic.example.model.BarDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BarDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BarDataOnDemand: @Component;
    
    private Random BarDataOnDemand.rnd = new SecureRandom();
    
    private List<Bar> BarDataOnDemand.data;
    
    public Bar BarDataOnDemand.getNewTransientBar(int index) {
        Bar obj = new Bar();
        setName(obj, index);
        setNum(obj, index);
        return obj;
    }
    
    public void BarDataOnDemand.setName(Bar obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void BarDataOnDemand.setNum(Bar obj, int index) {
        Integer num = new Integer(index);
        obj.setNum(num);
    }
    
    public Bar BarDataOnDemand.getSpecificBar(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Bar obj = data.get(index);
        Long id = obj.getId();
        return Bar.findBar(id);
    }
    
    public Bar BarDataOnDemand.getRandomBar() {
        init();
        Bar obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Bar.findBar(id);
    }
    
    public boolean BarDataOnDemand.modifyBar(Bar obj) {
        return false;
    }
    
    public void BarDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Bar.findBarEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Bar' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Bar>();
        for (int i = 0; i < 10; i++) {
            Bar obj = getNewTransientBar(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
