// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.example.model;

import com.bytepoxic.example.model.BarDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BarDataOnDemand_Roo_Configurable {
    
    declare @type: BarDataOnDemand: @Configurable;
    
}
