// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.example.model;

import com.bytepoxic.example.model.Bar;
import com.bytepoxic.example.model.BarDataOnDemand;
import com.bytepoxic.example.model.BarIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BarIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BarIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BarIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BarIntegrationTest: @Transactional;
    
    @Autowired
    BarDataOnDemand BarIntegrationTest.dod;
    
    @Test
    public void BarIntegrationTest.testCountBars() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        long count = Bar.countBars();
        Assert.assertTrue("Counter for 'Bar' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BarIntegrationTest.testFindBar() {
        Bar obj = dod.getRandomBar();
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide an identifier", id);
        obj = Bar.findBar(id);
        Assert.assertNotNull("Find method for 'Bar' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Bar' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BarIntegrationTest.testFindAllBars() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        long count = Bar.countBars();
        Assert.assertTrue("Too expensive to perform a find all test for 'Bar', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Bar> result = Bar.findAllBars();
        Assert.assertNotNull("Find all method for 'Bar' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Bar' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BarIntegrationTest.testFindBarEntries() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        long count = Bar.countBars();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Bar> result = Bar.findBarEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Bar' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Bar' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BarIntegrationTest.testFlush() {
        Bar obj = dod.getRandomBar();
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide an identifier", id);
        obj = Bar.findBar(id);
        Assert.assertNotNull("Find method for 'Bar' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBar(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Bar' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BarIntegrationTest.testMergeUpdate() {
        Bar obj = dod.getRandomBar();
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide an identifier", id);
        obj = Bar.findBar(id);
        boolean modified =  dod.modifyBar(obj);
        Integer currentVersion = obj.getVersion();
        Bar merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Bar' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BarIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", dod.getRandomBar());
        Bar obj = dod.getNewTransientBar(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Bar' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Bar' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BarIntegrationTest.testRemove() {
        Bar obj = dod.getRandomBar();
        Assert.assertNotNull("Data on demand for 'Bar' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bar' failed to provide an identifier", id);
        obj = Bar.findBar(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Bar' with identifier '" + id + "'", Bar.findBar(id));
    }
    
}
