// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import com.bytepoxic.core.model.AppRole;
import com.bytepoxic.core.model.AppRoleDataOnDemand;
import com.bytepoxic.core.model.AppRoleIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppRoleIntegrationTest: @Transactional;
    
    @Autowired
    AppRoleDataOnDemand AppRoleIntegrationTest.dod;
    
    @Test
    public void AppRoleIntegrationTest.testCountAppRoles() {
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", dod.getRandomAppRole());
        long count = AppRole.countAppRoles();
        Assert.assertTrue("Counter for 'AppRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppRoleIntegrationTest.testFindAppRole() {
        AppRole obj = dod.getRandomAppRole();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to provide an identifier", id);
        obj = AppRole.findAppRole(id);
        Assert.assertNotNull("Find method for 'AppRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppRoleIntegrationTest.testFindAllAppRoles() {
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", dod.getRandomAppRole());
        long count = AppRole.countAppRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppRole> result = AppRole.findAllAppRoles();
        Assert.assertNotNull("Find all method for 'AppRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppRoleIntegrationTest.testFindAppRoleEntries() {
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", dod.getRandomAppRole());
        long count = AppRole.countAppRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppRole> result = AppRole.findAppRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppRoleIntegrationTest.testFlush() {
        AppRole obj = dod.getRandomAppRole();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to provide an identifier", id);
        obj = AppRole.findAppRole(id);
        Assert.assertNotNull("Find method for 'AppRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppRole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AppRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppRoleIntegrationTest.testMergeUpdate() {
        AppRole obj = dod.getRandomAppRole();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to provide an identifier", id);
        obj = AppRole.findAppRole(id);
        boolean modified =  dod.modifyAppRole(obj);
        Integer currentVersion = obj.getVersion();
        AppRole merged = (AppRole)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AppRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppRoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", dod.getRandomAppRole());
        AppRole obj = dod.getNewTransientAppRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AppRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppRoleIntegrationTest.testRemove() {
        AppRole obj = dod.getRandomAppRole();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRole' failed to provide an identifier", id);
        obj = AppRole.findAppRole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppRole' with identifier '" + id + "'", AppRole.findAppRole(id));
    }
    
}
