// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import org.springframework.stereotype.Component;

privileged aspect EmailDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmailDataOnDemand: @Component;
    
    private Random EmailDataOnDemand.rnd = new SecureRandom();
    
    private List<Email> EmailDataOnDemand.data;
    
    public Email EmailDataOnDemand.getNewTransientEmail(int index) {
        Email obj = new Email();
        setEmailAddress(obj, index);
        setOwner(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void EmailDataOnDemand.setEmailAddress(Email obj, int index) {
        String emailAddress = "foo" + index + "@bar.com";
        if (emailAddress.length() > 64) {
            emailAddress = new Random().nextInt(10) + emailAddress.substring(1, 64);
        }
        obj.setEmailAddress(emailAddress);
    }
    
    public void EmailDataOnDemand.setOwner(Email obj, int index) {
        Person owner = null;
        obj.setOwner(owner);
    }
    
    public void EmailDataOnDemand.setType(Email obj, int index) {
        EmailType type = EmailType.class.getEnumConstants()[0];
        obj.setType(type);
    }
    
    public Email EmailDataOnDemand.getSpecificEmail(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Email obj = data.get(index);
        Long id = obj.getId();
        return Email.findEmail(id);
    }
    
    public Email EmailDataOnDemand.getRandomEmail() {
        init();
        Email obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Email.findEmail(id);
    }
    
    public boolean EmailDataOnDemand.modifyEmail(Email obj) {
        return false;
    }
    
    public void EmailDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Email.findEmailEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Email' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Email>();
        for (int i = 0; i < 10; i++) {
            Email obj = getNewTransientEmail(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
