// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import com.bytepoxic.core.model.NationalityDataOnDemand;
import com.bytepoxic.core.model.NationalityIntegrationTest;
import com.bytepoxic.core.service.LocationService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NationalityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NationalityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NationalityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NationalityIntegrationTest: @Transactional;
    
    @Autowired
    NationalityDataOnDemand NationalityIntegrationTest.dod;
    
    @Autowired
    LocationService NationalityIntegrationTest.locationService;
    
    @Test
    public void NationalityIntegrationTest.testCountAllNationalitys() {
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", dod.getRandomNationality());
        long count = locationService.countAllNationalitys();
        Assert.assertTrue("Counter for 'Nationality' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NationalityIntegrationTest.testFindNationality() {
        Nationality obj = dod.getRandomNationality();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to provide an identifier", id);
        obj = locationService.findNationality(id);
        Assert.assertNotNull("Find method for 'Nationality' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Nationality' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NationalityIntegrationTest.testFindAllNationalitys() {
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", dod.getRandomNationality());
        long count = locationService.countAllNationalitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Nationality', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Nationality> result = locationService.findAllNationalitys();
        Assert.assertNotNull("Find all method for 'Nationality' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Nationality' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NationalityIntegrationTest.testFindNationalityEntries() {
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", dod.getRandomNationality());
        long count = locationService.countAllNationalitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Nationality> result = locationService.findNationalityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Nationality' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Nationality' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NationalityIntegrationTest.testFlush() {
        Nationality obj = dod.getRandomNationality();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to provide an identifier", id);
        obj = locationService.findNationality(id);
        Assert.assertNotNull("Find method for 'Nationality' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNationality(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Nationality' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NationalityIntegrationTest.testUpdateNationalityUpdate() {
        Nationality obj = dod.getRandomNationality();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to provide an identifier", id);
        obj = locationService.findNationality(id);
        boolean modified =  dod.modifyNationality(obj);
        Integer currentVersion = obj.getVersion();
        Nationality merged = (Nationality)locationService.updateNationality(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Nationality' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NationalityIntegrationTest.testSaveNationality() {
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", dod.getRandomNationality());
        Nationality obj = dod.getNewTransientNationality(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Nationality' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Nationality' identifier to be null", obj.getId());
        locationService.saveNationality(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Nationality' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NationalityIntegrationTest.testDeleteNationality() {
        Nationality obj = dod.getRandomNationality();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Nationality' failed to provide an identifier", id);
        obj = locationService.findNationality(id);
        locationService.deleteNationality(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Nationality' with identifier '" + id + "'", locationService.findNationality(id));
    }
    
}
