// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.model;

import com.bytepoxic.core.model.Phone;
import com.bytepoxic.core.model.PhoneDataOnDemand;
import com.bytepoxic.core.model.PhoneIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PhoneIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhoneIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhoneIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PhoneIntegrationTest: @Transactional;
    
    @Autowired
    PhoneDataOnDemand PhoneIntegrationTest.dod;
    
    @Test
    public void PhoneIntegrationTest.testCountPhones() {
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", dod.getRandomPhone());
        long count = Phone.countPhones();
        Assert.assertTrue("Counter for 'Phone' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhoneIntegrationTest.testFindPhone() {
        Phone obj = dod.getRandomPhone();
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phone' failed to provide an identifier", id);
        obj = Phone.findPhone(id);
        Assert.assertNotNull("Find method for 'Phone' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Phone' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PhoneIntegrationTest.testFindAllPhones() {
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", dod.getRandomPhone());
        long count = Phone.countPhones();
        Assert.assertTrue("Too expensive to perform a find all test for 'Phone', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Phone> result = Phone.findAllPhones();
        Assert.assertNotNull("Find all method for 'Phone' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Phone' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhoneIntegrationTest.testFindPhoneEntries() {
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", dod.getRandomPhone());
        long count = Phone.countPhones();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Phone> result = Phone.findPhoneEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Phone' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Phone' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhoneIntegrationTest.testFlush() {
        Phone obj = dod.getRandomPhone();
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phone' failed to provide an identifier", id);
        obj = Phone.findPhone(id);
        Assert.assertNotNull("Find method for 'Phone' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhone(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Phone' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhoneIntegrationTest.testMergeUpdate() {
        Phone obj = dod.getRandomPhone();
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phone' failed to provide an identifier", id);
        obj = Phone.findPhone(id);
        boolean modified =  dod.modifyPhone(obj);
        Integer currentVersion = obj.getVersion();
        Phone merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Phone' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhoneIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", dod.getRandomPhone());
        Phone obj = dod.getNewTransientPhone(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Phone' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Phone' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Phone' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PhoneIntegrationTest.testRemove() {
        Phone obj = dod.getRandomPhone();
        Assert.assertNotNull("Data on demand for 'Phone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phone' failed to provide an identifier", id);
        obj = Phone.findPhone(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Phone' with identifier '" + id + "'", Phone.findPhone(id));
    }
    
}
