// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.web;

import com.bytepoxic.core.web.LocationBean;
import java.io.Serializable;

privileged aspect LocationBean_Roo_Serializable {
    
    declare parents: LocationBean implements Serializable;
    
    private static final long LocationBean.serialVersionUID = 1L;
    
}
