// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.web.faces.bean;

import com.bytepoxic.core.web.faces.bean.EmailBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmailBean_Roo_Configurable {
    
    declare @type: EmailBean: @Configurable;
    
}
