// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.example.model;

import com.bytepoxic.example.model.Foo;
import com.bytepoxic.example.model.FooDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect FooDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FooDataOnDemand: @Component;
    
    private Random FooDataOnDemand.rnd = new SecureRandom();
    
    private List<Foo> FooDataOnDemand.data;
    
    public Foo FooDataOnDemand.getNewTransientFoo(int index) {
        Foo obj = new Foo();
        setName(obj, index);
        setNum(obj, index);
        return obj;
    }
    
    public void FooDataOnDemand.setName(Foo obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void FooDataOnDemand.setNum(Foo obj, int index) {
        Integer num = new Integer(index);
        obj.setNum(num);
    }
    
    public Foo FooDataOnDemand.getSpecificFoo(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Foo obj = data.get(index);
        Long id = obj.getId();
        return Foo.findFoo(id);
    }
    
    public Foo FooDataOnDemand.getRandomFoo() {
        init();
        Foo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Foo.findFoo(id);
    }
    
    public boolean FooDataOnDemand.modifyFoo(Foo obj) {
        return false;
    }
    
    public void FooDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Foo.findFooEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Foo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Foo>();
        for (int i = 0; i < 10; i++) {
            Foo obj = getNewTransientFoo(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
