// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bytepoxic.core.web.converter;

import com.bytepoxic.core.web.converter.NationalityConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect NationalityConverter_Roo_Configurable {
    
    declare @type: NationalityConverter: @Configurable;
    
}
